export enum DateFormat {
  YYYY_MM_DD = 'YYYY-MM-DD',
  DD_MM_YYYY = 'DD/MM/YYYY',
  MM_DD_YYYY = 'MM/DD/YYYY',
  DD_MMM_YYYY = 'DD MMM YYYY',
  MMM_DD_YYYY = 'MMM DD, YYYY',
  YYYY_MM_DD_SLASH = 'YYYY/MM/DD'
}
